Auto-port 4.1: Mark LoggingHandlerTest with @Isolated to fix flaky build (#16340)
Auto-port of #16338 to 4.1
Cherry-picked commit: 4e38d602bc8a0e4d615c656e9335cdc4a721c506

---
Motivation:

As LoggingHandlerTest depends on static state we should better mark it
as `@Isolated` so we not mess up the state sometimes by running test
concurrently. Failing to do so can cause issues like:

```
2026-02-21T04:13:33.0279489Z [ERROR] io.netty.handler.logging.LoggingHandlerTest -- Time elapsed: 0.095 s <<< ERROR!
2026-02-21T04:13:33.0281038Z java.lang.ExceptionInInitializerError
2026-02-21T04:13:33.0282266Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2026-02-21T04:13:33.0284143Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
2026-02-21T04:13:33.0285193Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
2026-02-21T04:13:33.0286182Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
2026-02-21T04:13:33.0287200Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
2026-02-21T04:13:33.0288167Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2026-02-21T04:13:33.0289364Z 	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.logging.LoggingHandlerTest
2026-02-21T04:13:33.0290429Z 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2026-02-21T04:13:33.0291123Z 		at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2026-02-21T04:13:33.0291996Z 		at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
2026-02-21T04:13:33.0292740Z 		... 5 more
2026-02-21T04:13:33.0294696Z Caused by: java.lang.ClassCastException: class org.slf4j.helpers.SubstituteLogger cannot be cast to class ch.qos.logback.classic.Logger (org.slf4j.helpers.SubstituteLogger and ch.qos.logback.classic.Logger are in unnamed module of loader 'app')
2026-02-21T04:13:33.0296729Z 	at io.netty.handler.logging.LoggingHandlerTest.<clinit>(LoggingHandlerTest.java:61)
2026-02-21T04:13:33.0297699Z 	... 6 more
```

Modifications:

Add `@Isolated` annotation to test class

Result:

No more test-failures

Co-authored-by: Norman Maurer <norman_maurer@apple.com>